# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 18:44
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_candidato', models.CharField(max_length=40)),
                ('segundonombre_candidato', models.CharField(blank=True, max_length=40)),
                ('apellido_candidato', models.CharField(blank=True, max_length=50)),
                ('segundoapellido_candidato', models.CharField(blank=True, max_length=50)),
                ('web_candidato', models.URLField(blank=True, default='')),
                ('alias_candidato', models.CharField(blank=True, default='', max_length=70)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CategoriaPropuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_categoria', models.CharField(max_length=60)),
                ('descripcion_categoria', models.CharField(max_length=1000)),
                ('color_categoria', colorfield.fields.ColorField(default='#FF0000', max_length=10)),
            ],
            options={
                'ordering': ['-id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IntentoVisitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intento_browser', models.PositiveSmallIntegerField(default=1)),
                ('intento_db', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_partido', models.CharField(max_length=100, unique=True)),
                ('web_partido', models.URLField(blank=True, default='')),
                ('color_partido', colorfield.fields.ColorField(default='#FF0000', max_length=10)),
                ('logo_partido', models.ImageField(upload_to='')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_propuesta', models.CharField(max_length=2000)),
                ('entra_propuesta', models.BooleanField(default=False)),
                ('descripcion_propuesta', models.CharField(max_length=2000)),
                ('pregunta_propuesta', models.CharField(default='?', max_length=2000)),
                ('categoria_propuesta', models.ForeignKey(default=99, on_delete=django.db.models.deletion.SET_DEFAULT, to='quiz.CategoriaPropuesta')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RelPropuestas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificacion', models.CharField(blank=True, default='', max_length=2000)),
                ('paginadelplan', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('valor_propuesta', models.SmallIntegerField(blank=True, choices=[(-1, 'En desacuerdo -'), (0, 'Neutral'), (1, 'De acuerdo')], default=None, null=True)),
                ('candidato_relpropuestas', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Candidato')),
                ('propuesta_relpropuestas', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Propuesta')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_res', models.SmallIntegerField(blank=True, choices=[(-1, 'En desacuerdo -'), (0, 'Neutral'), (1, 'De acuerdo')], default=None, null=True)),
                ('importancia_res', models.SmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=None, null=True)),
                ('tiempo_res', models.DurationField(blank=True, null=True)),
                ('intento_res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.IntentoVisitante')),
                ('pregunta_res', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Propuesta')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('ip_res', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('sospechoso', models.BooleanField(default=False)),
                ('baneado', models.BooleanField(default=False)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='intentovisitante',
            name='visitante_intento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Visitante'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='partido_candidato',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Partido'),
        ),
        migrations.AlterUniqueTogether(
            name='relpropuestas',
            unique_together=set([('propuesta_relpropuestas', 'candidato_relpropuestas')]),
        ),
        migrations.AlterUniqueTogether(
            name='intentovisitante',
            unique_together=set([('visitante_intento', 'intento_db')]),
        ),
        migrations.AlterUniqueTogether(
            name='candidato',
            unique_together=set([('nombre_candidato', 'apellido_candidato')]),
        ),
    ]
