# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='categoria_propuesta',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.SET_DEFAULT, to='quiz.CategoriaPropuesta'),
        ),
    ]
