# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20160202_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriapropuesta',
            options={'managed': True, 'ordering': ['-id']},
        ),
    ]
