# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20160203_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='logo_partido',
            field=models.ImageField(default='img', upload_to=''),
            preserve_default=False,
        ),
    ]
