# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20160204_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoVisitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intento_browser', models.PositiveSmallIntegerField(default=1)),
                ('intento_db', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='respuesta',
            old_name='respuesta',
            new_name='respuesta_res',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='visitante_res',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='id',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='intento_res',
        ),
        migrations.AddField(
            model_name='visitante',
            name='baneado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitante',
            name='sospechoso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='ip_res',
            field=models.GenericIPAddressField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='intentovisitante',
            name='visitante_intento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Visitante'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='intento_res',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quiz.IntentoVisitante'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='intentovisitante',
            unique_together=set([('visitante_intento', 'intento_db')]),
        ),
    ]
