# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20160204_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='tiempo_res',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
