# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 03:03
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20160205_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriapropuesta',
            name='color_categoria',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=10),
        ),
        migrations.AlterField(
            model_name='partido',
            name='web_partido',
            field=models.URLField(blank=True, default=''),
        ),
    ]
