# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20160208_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relpropuestas',
            name='fuerza',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='importancia_res',
            field=models.SmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (3, '2'), (3, '3'), (4, '4')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='relpropuestas',
            name='justificacion',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='relpropuestas',
            name='valor_propuesta',
            field=models.SmallIntegerField(blank=True, choices=[(-1, 'En desacuerdo -'), (0, 'Neutral'), (1, 'De acuerdo')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='respuesta_res',
            field=models.SmallIntegerField(blank=True, choices=[(-1, 'En desacuerdo -'), (0, 'Neutral'), (1, 'De acuerdo')], default=None, null=True),
        ),
    ]
