# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20160211_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='importancia_res',
            field=models.SmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=None, null=True),
        ),
    ]
