# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 00:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0008_auto_20160208_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion_RelPropuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_subida', models.DateTimeField(auto_now_add=True)),
                ('justificacion', models.TextField(blank=True, max_length=2000)),
                ('fuente', models.CharField(choices=[('Plan_de_Gobierno', 'Plan de Gobierno'), ('Entrevista_TV', 'Entrevista (TV)'), ('Entrevista_Escrita', 'Entrevista (Escrita)'), ('Entrevista_Radio', 'Entrevista (Radio)')], default='Plan_de_Gobierno', max_length=25)),
                ('valor_propuesta', models.SmallIntegerField(choices=[(-3, 'En desacuerdo ---'), (-2, 'En desacuerdo --'), (-1, 'En desacuerdo -'), (0, 'Neutral ='), (1, 'De acuerdo +'), (2, 'De acuerdo ++'), (3, 'De acuerdo +++')], default=0)),
                ('paginadelplan', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('link_fuente', models.URLField(blank=True)),
                ('relpropuesta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.RelPropuestas')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otros', 'Otros'), ('', 'blank')], default='', max_length=10)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TokenUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre_apellido', models.CharField(blank=True, default='', max_length=60)),
                ('facebook', models.URLField(blank=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='token',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='codificacion.TokenUsuario'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opinion_relpropuesta',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='codificacion.PerfilUsuario'),
        ),
    ]
