# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codificacion', '0002_auto_20160210_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='gender',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otros', 'Otros'), ('', 'No especificar')], default='', max_length=10, null=True),
        ),
    ]
