# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codificacion', '0003_auto_20160211_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion_relpropuesta',
            name='justificacion',
            field=models.TextField(blank=True, max_length=2000, verbose_name='justificación'),
        ),
        migrations.AlterField(
            model_name='opinion_relpropuesta',
            name='link_fuente',
            field=models.URLField(blank=True, verbose_name='URL de la fuente'),
        ),
        migrations.AlterField(
            model_name='opinion_relpropuesta',
            name='paginadelplan',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='página del Plan'),
        ),
        migrations.AlterField(
            model_name='opinion_relpropuesta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='codificacion.PerfilUsuario'),
        ),
        migrations.AlterField(
            model_name='opinion_relpropuesta',
            name='valor_propuesta',
            field=models.SmallIntegerField(choices=[(-1, 'En desacuerdo'), (0, 'Neutral'), (1, 'De acuerdo')], default=0, verbose_name='posición'),
        ),
        migrations.AlterUniqueTogether(
            name='opinion_relpropuesta',
            unique_together=set([('user', 'relpropuesta')]),
        ),
    ]
